"""initial schema

Revision ID: dd9678cdceb0
Revises: 
Create Date: 2026-06-19 22:04:57.114150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9678cdceb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon_class', sa.String(length=50), nullable=True),
    sa.Column('marketing_headline', sa.String(length=150), nullable=True),
    sa.Column('marketing_description', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('annual_token_allocation', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)

    op.create_table('audit_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tier_at_creation', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('device_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('device_token', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_authorized', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token')
    )
    with op.batch_alter_table('device_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_sessions_fingerprint_hash'), ['fingerprint_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('payment_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('authorize_net_txn_id', sa.String(length=100), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_records_user_id'), ['user_id'], unique=False)

    op.create_table('token_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pref_key', sa.String(length=200), nullable=False),
    sa.Column('pref_value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pref_key', name='uq_user_pref')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index('ix_user_pref_lookup', ['user_id', 'pref_key'], unique=False)

    op.create_table('user_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_user_product')
    )
    with op.batch_alter_table('user_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_products_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_products_user_id'), ['user_id'], unique=False)

    op.create_table('user_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_price_cents', sa.Integer(), nullable=False),
    sa.Column('token_balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('audit_check_completions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=False),
    sa.Column('check_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'check_id', name='uq_audit_check')
    )
    with op.batch_alter_table('audit_check_completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_check_completions_audit_id'), ['audit_id'], unique=False)

    op.create_table('audit_intakes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('site_types', sa.JSON(), nullable=True),
    sa.Column('rich_results_schemas', sa.JSON(), nullable=True),
    sa.Column('international', sa.Boolean(), nullable=True),
    sa.Column('site_size', sa.String(length=50), nullable=True),
    sa.Column('crawl_tool', sa.String(length=50), nullable=True),
    sa.Column('seo_tools', sa.JSON(), nullable=True),
    sa.Column('js_frameworks', sa.JSON(), nullable=True),
    sa.Column('has_ads', sa.Boolean(), nullable=True),
    sa.Column('brand_colors', sa.JSON(), nullable=True),
    sa.Column('narrative_voice', sa.String(length=50), nullable=True),
    sa.Column('has_server_logs', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id')
    )
    op.create_table('canvas_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('check_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canvas_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canvas_blocks_audit_id'), ['audit_id'], unique=False)

    op.create_table('column_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_key', sa.String(length=100), nullable=False),
    sa.Column('user_header', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'canonical_key', name='uq_audit_column')
    )
    with op.batch_alter_table('column_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_column_mappings_audit_id'), ['audit_id'], unique=False)

    op.create_table('content_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=True),
    sa.Column('check_id', sa.String(length=100), nullable=False),
    sa.Column('content_path', sa.String(length=255), nullable=False),
    sa.Column('anchor_exact', sa.Text(), nullable=False),
    sa.Column('anchor_prefix', sa.String(length=100), nullable=True),
    sa.Column('anchor_suffix', sa.String(length=100), nullable=True),
    sa.Column('anchor_start_offset', sa.Integer(), nullable=True),
    sa.Column('anchor_end_offset', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_comments_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_comments_check_id'), ['check_id'], unique=False)

    op.create_table('content_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=True),
    sa.Column('check_id', sa.String(length=100), nullable=False),
    sa.Column('field_path', sa.String(length=255), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('proposed_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proposed_by_id', sa.String(length=36), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_overrides_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_overrides_check_id'), ['check_id'], unique=False)
        batch_op.create_index('ix_override_lookup', ['check_id', 'field_path', 'status'], unique=False)

    op.create_table('crawl_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_files_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_files_user_id'), ['user_id'], unique=False)

    op.create_table('comment_replies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comment_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['content_comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment_replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_replies_comment_id'), ['comment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_replies_comment_id'))

    op.drop_table('comment_replies')
    with op.batch_alter_table('crawl_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_files_user_id'))
        batch_op.drop_index(batch_op.f('ix_crawl_files_audit_id'))

    op.drop_table('crawl_files')
    with op.batch_alter_table('content_overrides', schema=None) as batch_op:
        batch_op.drop_index('ix_override_lookup')
        batch_op.drop_index(batch_op.f('ix_content_overrides_check_id'))
        batch_op.drop_index(batch_op.f('ix_content_overrides_audit_id'))

    op.drop_table('content_overrides')
    with op.batch_alter_table('content_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_comments_check_id'))
        batch_op.drop_index(batch_op.f('ix_content_comments_audit_id'))

    op.drop_table('content_comments')
    with op.batch_alter_table('column_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_column_mappings_audit_id'))

    op.drop_table('column_mappings')
    with op.batch_alter_table('canvas_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canvas_blocks_audit_id'))

    op.drop_table('canvas_blocks')
    op.drop_table('audit_intakes')
    with op.batch_alter_table('audit_check_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_check_completions_audit_id'))

    op.drop_table('audit_check_completions')
    op.drop_table('user_subscriptions')
    with op.batch_alter_table('user_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_products_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_products_product_id'))

    op.drop_table('user_products')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index('ix_user_pref_lookup')

    op.drop_table('user_preferences')
    with op.batch_alter_table('token_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_transactions_user_id'))

    op.drop_table('token_transactions')
    with op.batch_alter_table('payment_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_records_user_id'))

    op.drop_table('payment_records')
    with op.batch_alter_table('device_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_sessions_fingerprint_hash'))

    op.drop_table('device_sessions')
    with op.batch_alter_table('audit_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_sessions_user_id'))

    op.drop_table('audit_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
